export const CURATED_LANDMARKS = [
  // DC memorials
  {
    key: "lincoln_memorial",
    name: "Lincoln Memorial",
    address: "2 Lincoln Memorial Cir NW, Washington, DC",
    lat: 38.8893,
    lng: -77.0502,
    region: "Washington, DC",
    collectionKeys: ["dc_memorials"],
  },
  {
    key: "washington_monument",
    name: "Washington Monument",
    address: "2 15th St NW, Washington, DC",
    lat: 38.8895,
    lng: -77.0353,
    region: "Washington, DC",
    collectionKeys: ["dc_memorials"],
  },
  {
    key: "jefferson_memorial",
    name: "Jefferson Memorial",
    address: "16 E Basin Dr SW, Washington, DC",
    lat: 38.8814,
    lng: -77.0365,
    region: "Washington, DC",
    collectionKeys: ["dc_memorials"],
  },

  // California ballparks
  {
    key: "dodger_stadium",
    name: "Dodger Stadium",
    address: "1000 Vin Scully Ave, Los Angeles, CA",
    lat: 34.0739,
    lng: -118.24,
    region: "California",
    collectionKeys: ["ca_ballparks"],
  },
  {
    key: "angel_stadium",
    name: "Angel Stadium",
    address: "2000 E Gene Autry Way, Anaheim, CA",
    lat: 33.8003,
    lng: -117.8827,
    region: "California",
    collectionKeys: ["ca_ballparks"],
  },
  {
    key: "petco_park",
    name: "Petco Park",
    address: "100 Park Blvd, San Diego, CA",
    lat: 32.7073,
    lng: -117.1566,
    region: "California",
    collectionKeys: ["ca_ballparks"],
  },

  // California beaches
{
    key: "santa_monica_beach",
    name: "Santa Monica Beach",
    address: "Santa Monica Beach, Santa Monica, CA",
    lat: 34.0094,
    lng: -118.4973,
    region: "California",
    collectionKeys: ["ca_beaches"],
},
{
    key: "venice_beach",
    name: "Venice Beach",
    address: "Venice Beach, Los Angeles, CA",
    lat: 33.985,
    lng: -118.4695,
    region: "California",
    collectionKeys: ["ca_beaches"],  },
{
    key: "laguna_beach",
    name: "Laguna Beach",
    address: "Laguna Beach, CA",
    lat: 33.5427,
    lng: -117.7854,
    region: "California",
    collectionKeys: ["ca_beaches"],
},
{
    key: "huntington_beach",
    name: "Huntington Beach",
    address: "Huntington Beach, CA",
    lat: 33.6595,
    lng: -117.9988,
    region: "California",
    collectionKeys: ["ca_beaches"],
 },
{
    key: "hermosa_beach",
    name: "Hermosa Beach",
    address: "Hermosa Beach, CA",
    lat: 33.8622,
    lng: -118.3995,
    region: "California",
    collectionKeys: ["ca_beaches"],
},
{
    key: "redondo_beach",
    name: "Redondo Beach",
    address: "Redondo Beach, CA",
    lat: 33.8492,
    lng: -118.3884,
    region: "California",
    collectionKeys: ["ca_beaches"],
},
{
    key: "cabrillo_beach",
    name: "Cabrillo Beach",
    address: "Cabrillo Beach, San Pedro, CA",
    lat: 33.7066,
    lng: -118.2795,
    region: "California",
    collectionKeys: ["ca_beaches"],
},

  // California universities
  {
    key: "csulb",
    name: "California State University, Long Beach",
    address: "1250 Bellflower Blvd, Long Beach, CA",
    lat: 33.7838,
    lng: -118.1141,
    region: "California",
    collectionKeys: ["ca_universities"],
  },
  {
    key: "ucla",
    name: "University of California, Los Angeles",
    address: "405 Hilgard Ave, Los Angeles, CA",
    lat: 34.0689,
    lng: -118.4452,
    region: "California",
    collectionKeys: ["ca_universities"],
  },
  {
    key: "uc_berkeley",
    name: "University of California, Berkeley",
    address: "Berkeley, CA",
    lat: 37.8719,
    lng: -122.2585,
    region: "California",
    collectionKeys: ["ca_universities"],
  },
  {
    key: "ucsd",
    name: "University of California, San Diego",
    address: "9500 Gilman Dr, La Jolla, CA",
    lat: 32.8801,
    lng: -117.234,
    region: "California",
    collectionKeys: ["ca_universities"],
  },
];